esphome:
  name: bed_occupancy_sensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Occupancy Sensor"
    password: "nmM5xEAz5XjM"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  
web_server:
  port: 80
  
sensor:
  - platform: hx711
    name: "HX711 Value"
    id: bed_sensor
    dout_pin: D0
    clk_pin: D1
    gain: 128
    update_interval: 1s
    filters:
      - calibrate_linear:
        - 1574661 -> 0
        - 3360000 -> 86
    unit_of_measurement: kg

binary_sensor:
  - platform: template
    name: bed_occupancy
    lambda: |- 
     return id(bed_sensor).state > 40;